# Generated by Django 3.1.7 on 2021-03-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_studentsinclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('assignment_name', models.CharField(max_length=254)),
                ('assignment', models.FileField(upload_to='assignment')),
                ('students', models.ManyToManyField(related_name='student_assignment', to='app1.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignment', to='app1.teacher')),
            ],
        ),
    ]
