# Generated by Django 3.1.7 on 2021-03-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('dor', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='movie_images')),
            ],
            options={
                'verbose_name': 'Movie Details',
                'verbose_name_plural': 'Movie Details',
            },
        ),
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('review', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.moviedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movie Review',
                'verbose_name_plural': 'Movie Reviews',
                'ordering': ['date'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
